apiVersion: v1
kind: Service
metadata:
  name: graph-tools-frontend-service
spec:
  type: NodePort
  selector:
    app: graph-tools-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000